global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # --- APP 1: NOMAS COLYSEUS---
  - job_name: "nomas-colyseus"
    scrape_interval: 10s
    # If we don't declare scrape_interval, it will use the default 15s
    static_configs:
      - targets: ["host.docker.internal:3002"] # Address and port of Nomas Colyseus
